"""Hosted Git providers."""

from .c8_phase2 import (
    C8Phase2Blocked,
    C8Phase2Unverifiable,
    EffectiveMainRules,
    MergeQueueConfiguration,
    RequiredChecksConfiguration,
    parse_branch_protection_checks,
    parse_effective_main_rules,
    parse_merge_queue,
    parse_merge_queue_configuration,
    parse_required_checks,
    parse_rules,
)
from .c8_preflight_snapshot import (
    C8GitHubPreflightSnapshot,
    C8HostedPreflightSnapshot,
    C8PreflightSnapshotAdapter,
    C8PreflightSnapshotUnverifiable,
    GitHubC8PreflightAdapter,
    GitHubC8PreflightSnapshot,
)
from .c8_snapshot import C8GitHubSnapshotAdapter, C8SnapshotUnverifiable, GitHubC8SnapshotAdapter
from .c8_workflow_semantics import (
    C8WorkflowSemantics,
    C8WorkflowSemanticsUnverifiable,
    parse_c8_workflow_semantics,
)
from .campaign import GitHubCampaignProvider
from .github import (
    GitHubEvidenceSnapshot,
    GitHubIntegrationProvider,
    GitHubProtectionPolicy,
    GitHubProvider,
    GitHubPullRequestBinding,
    GitHubPullRequestDiscovery,
    GitHubRefObservation,
    GitHubRESTProvider,
    GitHubRollbackTopology,
    github_repository_digest,
)
from .github_transport import GitHubJsonTransport
from .protected_main import (
    MainGraduationAttester,
    MainMergeGroupObservation,
    MainProtectedProvider,
    MainPullRequestObservation,
    MainRefObservation,
    MainRepositoryObservation,
    ProtectedMainAttestationAdapter,
    ProtectedMainAttester,
    ProtectedMainGitHubProvider,
    ProtectedMainProvider,
    ProtectedMainProviderError,
    ProtectedMainRejected,
    ProtectedMainSnapshot,
)

__all__ = [
    "C8GitHubPreflightSnapshot",
    "C8GitHubSnapshotAdapter",
    "C8HostedPreflightSnapshot",
    "C8Phase2Blocked",
    "C8Phase2Unverifiable",
    "C8PreflightSnapshotAdapter",
    "C8PreflightSnapshotUnverifiable",
    "C8SnapshotUnverifiable",
    "C8WorkflowSemantics",
    "C8WorkflowSemanticsUnverifiable",
    "EffectiveMainRules",
    "GitHubC8PreflightAdapter",
    "GitHubC8PreflightSnapshot",
    "GitHubC8SnapshotAdapter",
    "GitHubCampaignProvider",
    "GitHubEvidenceSnapshot",
    "GitHubIntegrationProvider",
    "GitHubJsonTransport",
    "GitHubProtectionPolicy",
    "GitHubProvider",
    "GitHubPullRequestBinding",
    "GitHubPullRequestDiscovery",
    "GitHubRESTProvider",
    "GitHubRefObservation",
    "GitHubRollbackTopology",
    "MainGraduationAttester",
    "MainMergeGroupObservation",
    "MainProtectedProvider",
    "MainPullRequestObservation",
    "MainRefObservation",
    "MainRepositoryObservation",
    "MergeQueueConfiguration",
    "ProtectedMainAttestationAdapter",
    "ProtectedMainAttester",
    "ProtectedMainGitHubProvider",
    "ProtectedMainProvider",
    "ProtectedMainProviderError",
    "ProtectedMainRejected",
    "ProtectedMainSnapshot",
    "RequiredChecksConfiguration",
    "github_repository_digest",
    "parse_branch_protection_checks",
    "parse_c8_workflow_semantics",
    "parse_effective_main_rules",
    "parse_merge_queue",
    "parse_merge_queue_configuration",
    "parse_required_checks",
    "parse_rules",
]
