"""Export authoritative JSON Schemas from boundary models."""

import json
from pathlib import Path
from typing import Any

from avo_correlate.contracts import (
    AdmissionDecision,
    CampaignCompletionPlan,
    CampaignDiscoveryEvidence,
    CampaignFinalEvidenceRecord,
    CampaignOpenedEvidence,
    CampaignPreparationEvidence,
    CandidateManifest,
    CandidatePublicationBinding,
    EvaluationRecord,
    ExperimentSpec,
    FailedSoakAttestation,
    GitRefSnapshot,
    IntegrationCampaignEvidencePackage,
    IntegrationIntentTemplate,
    IntegrationMergeResult,
    IntegrationPromotionIntent,
    IntegrationPromotionReceipt,
    IntegrationPromotionReport,
    IntegrationProviderObservation,
    IntegrationProviderReconciliation,
    PolicyDecision,
    PromotionBundle,
    PromotionConfig,
    PromotionControllerConfig,
    PromotionDecision,
    PromotionDryRunInput,
    PromotionDryRunResult,
    PromotionLeaseEvidence,
    PromotionMutationAuthorization,
    PromotionProvenanceBinding,
    PromotionReplayReport,
    PromotionRequest,
    RollbackOperationQuarantine,
    RollbackPromotionBundleAuthorization,
    RollbackPublicationAuthorityConfig,
    RollbackPublicationAuthorization,
    RollbackRemoteAbsenceObservation,
    RollbackSnapshotRestoreFacts,
    VariationAttemptRecord,
    VariationSessionRequest,
    VariationSessionResult,
    WorkspaceComparison,
)
from avo_correlate.contracts.advisory import (
    AdvisoryEvaluationSummary,
    AdvisoryEvidenceItem,
    AdvisoryFinding,
    AdvisoryPatchReview,
    AdvisoryPatchReviewInput,
)
from avo_correlate.contracts.advisory_evaluation import (
    AdvisoryCaseScore,
    AdvisoryEvaluationCase,
    AdvisoryEvaluationReport,
    AdvisoryEvaluationResultManifest,
)
from avo_correlate.contracts.agent import AgentContext, AgentObservation, AgentTurn
from avo_correlate.contracts.base import StrictModel
from avo_correlate.contracts.inference import StructuredInferenceContext
from avo_correlate.contracts.integration_drill import (
    DrillEvidenceBinding,
    IntegrationDrillCaseResult,
    IntegrationDrillPlan,
    IntegrationDrillPromotionEvidenceManifest,
    IntegrationDrillResult,
    IntegrationDrillRollbackAuthorization,
    IntegrationDrillRollbackIntent,
    IntegrationDrillRollbackReceipt,
    IntegrationDrillSoakObservation,
    IntegrationRollbackRequest,
)
from avo_correlate.contracts.integration_live_rollback import LiveRollbackEvidencePackage
from avo_correlate.contracts.integration_live_rollback_completion import (
    LiveRollbackCheckEntry,
    LiveRollbackCompletionPackage,
    LiveRollbackManifestEvidence,
    LiveRollbackProtectionEntry,
    LiveRollbackPublicationEvidence,
    LiveRollbackPublicationOutcome,
    LiveRollbackPublicationPlan,
    LiveRollbackWorkflowEvidence,
)
from avo_correlate.contracts.main_graduation import (
    EligibilityLedgerStarted,
    MainAttestationManifest,
    MainCheckObservation,
    MainClaimedReleaseTransitionReceipt,
    MainCompletionPackage,
    MainCompositionArtifact,
    MainCompositionProof,
    MainDeltaManifest,
    MainExternalIdentity,
    MainGraduationAttempt,
    MainGraduationEligibilityRecord,
    MainGraduationIntent,
    MainGraduationPlan,
    MainInverseDeltaArtifact,
    MainLeaseEvidence,
    MainLeaseEvidenceReadRequest,
    MainLeaseEvidenceRecord,
    MainMergeGroupChecks,
    MainMergeGroupWebhookReceipt,
    MainMutationFenceResolution,
    MainMutationIntent,
    MainMutationReceipt,
    MainPreparationAuthorization,
    MainProtectionManifest,
    MainProviderPostStateObservation,
    MainProviderReceipt,
    MainQueueAdmissionObservation,
    MainQueueConfigurationObservation,
    MainQueueObservation,
    MainReconciliation,
    MainReleaseAuthorization,
    MainReleaseClaim,
    MainReleaseHoldObservation,
    MainReleaseIssuerBinding,
    MainReleaseTransitionReceipt,
    MainRollbackAuthorization,
    MainRollbackIntent,
    MainSourcePackageBinding,
    MainUnresolvedMutationFence,
    MainValidationIdentity,
)
from avo_correlate.contracts.model import ModelInvocationRecord, ModelRequest, ModelResponse
from avo_correlate.contracts.operations import (
    DryRunReport,
    PlatformOverheadReport,
    ReferenceScenarioResult,
)
from avo_correlate.contracts.plugins import PluginCapabilityManifest, SignedPluginManifest
from avo_correlate.contracts.projections import (
    ArtifactMetadataProjection,
    CandidateProjection,
    SessionProjection,
    SessionRuntimeProjection,
)
from avo_correlate.contracts.provenance import ProvenanceExport, VerificationReport
from avo_correlate.contracts.review import ReviewDecision, ReviewRequest, ReviewStatus
from avo_correlate.contracts.runtime import (
    AgentCompletion,
    EconomicUsageRecord,
    HarnessInvocationRecord,
    HarnessRuntimeProfile,
    ReconciliationCaseRecord,
    RuntimeCapabilityReport,
    RuntimeEvent,
    RuntimeInspection,
    RuntimeSessionRef,
)
from avo_correlate.contracts.sandbox import SandboxExecutionResult, SandboxExecutionSpec
from avo_correlate.contracts.search import SearchCandidate, SearchDecision, SearchState
from avo_correlate.contracts.supervisor import SupervisorDirective, SupervisorObservation
from avo_correlate.contracts.synthetic_validation import (
    SyntheticValidationAttempt,
    SyntheticValidationCompletionProof,
    SyntheticValidationCreateAuthorization,
    SyntheticValidationObservation,
    SyntheticValidationOutcome,
    SyntheticValidationPlan,
    SyntheticValidationRequest,
)
from avo_correlate.contracts.tools import CapabilityClaims, ToolInvocationRecord

MODELS: tuple[type[StrictModel], ...] = (
    ExperimentSpec,
    VariationSessionRequest,
    VariationSessionResult,
    VariationAttemptRecord,
    CandidateManifest,
    EvaluationRecord,
    AdmissionDecision,
    PolicyDecision,
    PromotionConfig,
    GitRefSnapshot,
    WorkspaceComparison,
    PromotionControllerConfig,
    PromotionDryRunInput,
    PromotionProvenanceBinding,
    PromotionBundle,
    PromotionDryRunResult,
    PromotionReplayReport,
    RollbackPromotionBundleAuthorization,
    PromotionRequest,
    PromotionDecision,
    IntegrationCampaignEvidencePackage,
    CampaignCompletionPlan,
    CampaignDiscoveryEvidence,
    CampaignFinalEvidenceRecord,
    CampaignOpenedEvidence,
    CampaignPreparationEvidence,
    CandidatePublicationBinding,
    RollbackPublicationAuthorityConfig,
    RollbackPublicationAuthorization,
    RollbackSnapshotRestoreFacts,
    RollbackOperationQuarantine,
    RollbackRemoteAbsenceObservation,
    IntegrationIntentTemplate,
    IntegrationMergeResult,
    IntegrationPromotionIntent,
    IntegrationPromotionReceipt,
    IntegrationPromotionReport,
    IntegrationProviderObservation,
    IntegrationProviderReconciliation,
    PromotionLeaseEvidence,
    PromotionMutationAuthorization,
    SandboxExecutionSpec,
    SandboxExecutionResult,
    DryRunReport,
    CapabilityClaims,
    ToolInvocationRecord,
    ModelRequest,
    ModelResponse,
    ModelInvocationRecord,
    ProvenanceExport,
    VerificationReport,
    SessionProjection,
    CandidateProjection,
    ArtifactMetadataProjection,
    AgentContext,
    AgentObservation,
    AgentTurn,
    StructuredInferenceContext,
    AdvisoryEvidenceItem,
    AdvisoryEvaluationSummary,
    AdvisoryPatchReviewInput,
    AdvisoryFinding,
    AdvisoryPatchReview,
    AdvisoryEvaluationCase,
    AdvisoryCaseScore,
    AdvisoryEvaluationReport,
    AdvisoryEvaluationResultManifest,
    SupervisorObservation,
    SupervisorDirective,
    SearchCandidate,
    SearchState,
    SearchDecision,
    ReviewRequest,
    ReviewDecision,
    ReviewStatus,
    PluginCapabilityManifest,
    SignedPluginManifest,
    ReferenceScenarioResult,
    PlatformOverheadReport,
    AgentCompletion,
    EconomicUsageRecord,
    HarnessInvocationRecord,
    HarnessRuntimeProfile,
    ReconciliationCaseRecord,
    RuntimeCapabilityReport,
    RuntimeEvent,
    RuntimeInspection,
    RuntimeSessionRef,
    SessionRuntimeProjection,
    SyntheticValidationObservation,
    SyntheticValidationRequest,
    SyntheticValidationPlan,
    SyntheticValidationOutcome,
    SyntheticValidationAttempt,
    SyntheticValidationCreateAuthorization,
    SyntheticValidationCompletionProof,
    DrillEvidenceBinding,
    IntegrationDrillSoakObservation,
    IntegrationDrillRollbackAuthorization,
    IntegrationDrillRollbackIntent,
    IntegrationDrillRollbackReceipt,
    IntegrationDrillCaseResult,
    IntegrationDrillPlan,
    IntegrationDrillPromotionEvidenceManifest,
    IntegrationDrillResult,
    IntegrationRollbackRequest,
    LiveRollbackEvidencePackage,
    LiveRollbackCompletionPackage,
    LiveRollbackCheckEntry,
    LiveRollbackManifestEvidence,
    LiveRollbackProtectionEntry,
    LiveRollbackPublicationEvidence,
    LiveRollbackPublicationOutcome,
    LiveRollbackPublicationPlan,
    LiveRollbackWorkflowEvidence,
    FailedSoakAttestation,
    EligibilityLedgerStarted,
    MainAttestationManifest,
    MainClaimedReleaseTransitionReceipt,
    MainCheckObservation,
    MainCompletionPackage,
    MainCompositionArtifact,
    MainCompositionProof,
    MainDeltaManifest,
    MainGraduationAttempt,
    MainGraduationEligibilityRecord,
    MainGraduationIntent,
    MainInverseDeltaArtifact,
    MainLeaseEvidence,
    MainLeaseEvidenceReadRequest,
    MainLeaseEvidenceRecord,
    MainGraduationPlan,
    MainMergeGroupChecks,
    MainMergeGroupWebhookReceipt,
    MainMutationFenceResolution,
    MainMutationIntent,
    MainMutationReceipt,
    MainPreparationAuthorization,
    MainProviderPostStateObservation,
    MainProviderReceipt,
    MainQueueConfigurationObservation,
    MainReleaseIssuerBinding,
    MainProtectionManifest,
    MainQueueAdmissionObservation,
    MainQueueObservation,
    MainReconciliation,
    MainReleaseAuthorization,
    MainReleaseClaim,
    MainReleaseHoldObservation,
    MainReleaseTransitionReceipt,
    MainRollbackAuthorization,
    MainRollbackIntent,
    MainSourcePackageBinding,
    MainValidationIdentity,
    MainExternalIdentity,
    MainUnresolvedMutationFence,
)


def export(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for model in MODELS:
        model_api: Any = model
        # Keep breaking contract versions side-by-side.  Every model currently
        # defaults to v1 except explicitly bumped contracts such as C4.
        schema_field = model_api.model_fields.get("schema_version")
        version = schema_field.default if schema_field is not None else 1
        destination = output_dir / f"{model_api.__name__}.v{version}.schema.json"
        destination.write_text(
            json.dumps(model_api.model_json_schema(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )


if __name__ == "__main__":
    export(Path("schemas"))
